country_mapping = {
     # Amérique du Nord
    "États-Unis d'Amérique": "United States",
    "Canada": "Canada",
    
    # Amérique Centrale et Caraïbes
    "Antigua-et-Barbuda": "Antigua and Barbuda",
    "Bahamas": "Bahamas",
    "Barbade": "Barbados",
    "Belize": "Belize",
    "Costa Rica": "Costa Rica",
    "Cuba": "Cuba",
    "Dominique": "Dominica",
    "El Salvador": "El Salvador",
    "Grenade": "Grenada",
    "Guatemala": "Guatemala",
    "Haïti": "Haiti",
    "Honduras": "Honduras",
    "Jamaïque": "Jamaica",
    "Nicaragua": "Nicaragua",
    "Panama": "Panama",
    "République dominicaine": "Dominican Republic",
    "Saint Kitts et Nevis": "Saint Kitts and Nevis",
    "Sainte Lucie": "Saint Lucia",
    "Saint Vincent et les Grenadines": "Saint Vincent and the Grenadines",
    "Trinité-et-Tobago": "Trinidad and Tobago",
    
    # Amérique du Sud
    "Argentine": "Argentina",
    "Bolivie (État plurinational de)": "Bolivia",
    "Brésil": "Brazil",
    "Chili": "Chile",
    "Colombie": "Colombia",
    "Équateur": "Ecuador",
    "Guyana": "Guyana",
    "Paraguay": "Paraguay",
    "Pérou": "Peru",
    "Suriname": "Suriname",
    "Uruguay": "Uruguay",
    "Venezuela (République bolivarienne du)": "Venezuela",
    
    # Europe
    "Albanie": "Albania",
    "Allemagne": "Germany",
    "Andorre": "Andorra",
    "Autriche": "Austria",
    "Bélarus": "Belarus",
    "Belgique": "Belgium",
    "Bosnie Herzégovine": "Bosnia and Herzegovina",
    "Bulgarie": "Bulgaria",
    "Chypre": "Cyprus",
    "Croatie": "Croatia",
    "Danemark": "Denmark",
    "Espagne": "Spain",
    "Estonie": "Estonia",
    "Fédération de Russie": "Russia",
    "Finlande": "Finland",
    "France": "France",
    "Géorgie": "Georgia",
    "Grèce": "Greece",
    "Groenland": "Greenland",
    "Hongrie": "Hungary",
    "Irlande": "Ireland",
    "Islande": "Iceland",
    "Italie": "Italy",
    "Lettonie": "Latvia",
    "Lituanie": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Macédoine du Nord": "North Macedonia",
    "Malte": "Malta",
    "Monténégro": "Montenegro",
    "Norvège": "Norway",
    "Pays-Bas (Royaume des)": "Netherlands",
    "Pologne": "Poland",
    "Portugal": "Portugal",
    "République de Moldova": "Moldova",
    "Roumanie": "Romania",
    "Royaume Uni de Grande Bretagne et d Irlande du Nord": "United Kingdom",
    "Serbie": "Serbia",
    "Slovaquie": "Slovakia",
    "Slovénie": "Slovenia",
    "Suède": "Sweden",
    "Suisse": "Switzerland",
    "Tchéquie": "Czech Republic",
    "Ukraine": "Ukraine",
    
    # Asie
    "Afghanistan": "Afghanistan",
    "Arabie saoudite": "Saudi Arabia",
    "Arménie": "Armenia",
    "Azerbaïdjan": "Azerbaijan",
    "Bahreïn": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Bhoutan": "Bhutan",
    "Brunéi Darussalam": "Brunei",
    "Cambodge": "Cambodia",
    "Chine": "China",
    "Chine, continentale": "China",
    "Chine - RAS de Hong-Kong": "Hong Kong",
    "Chine - RAS de Macao": "Macau",
    "Chine, Taiwan Province de": "Taiwan",
    "Émirats arabes unis": "United Arab Emirates",
    "Inde": "India",
    "Indonésie": "Indonesia",
    "Iran (République islamique d')": "Iran",
    "Iraq": "Iraq",
    "Israël": "Israel",
    "Japon": "Japan",
    "Jordanie": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kirghizistan": "Kyrgyzstan",
    "Koweït": "Kuwait",
    "Liban": "Lebanon",
    "Malaisie": "Malaysia",
    "Maldives": "Maldives",
    "Mongolie": "Mongolia",
    "Myanmar": "Myanmar",
    "Népal": "Nepal",
    "Oman": "Oman",
    "Ouzbékistan": "Uzbekistan",
    "Pakistan": "Pakistan",
    "Palestine": "Palestine",
    "Philippines": "Philippines",
    "Qatar": "Qatar",
    "République arabe syrienne": "Syria",
    "République de Corée": "South Korea",
    "République démocratique populaire lao": "Laos",
    "République populaire démocratique de Corée": "North Korea",
    "Singapour": "Singapore",
    "Sri Lanka": "Sri Lanka",
    "Tadjikistan": "Tajikistan",
    "Thaïlande": "Thailand",
    "Timor-Leste": "Timor-Leste",
    "Türkiye": "Turkey",
    "Turkménistan": "Turkmenistan",
    "Viet Nam": "Vietnam",
    "Yémen": "Yemen",
    
    # Afrique
    "Afrique du Sud": "South Africa",
    "Algérie": "Algeria",
    "Angola": "Angola",
    "Bénin": "Benin",
    "Botswana": "Botswana",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Cape Verde",
    "Cameroun": "Cameroon",
    "Comores": "Comoros",
    "Congo": "Republic of the Congo",
    "Côte d'Ivoire": "Ivory Coast",
    "Djibouti": "Djibouti",
    "Égypte": "Egypt",
    "Érythrée": "Eritrea",
    "Eswatini": "Eswatini",
    "Éthiopie": "Ethiopia",
    "Gabon": "Gabon",
    "Gambie": "Gambia",
    "Ghana": "Ghana",
    "Guinée": "Guinea",
    "Guinée Bissau": "Guinea-Bissau",
    "Guinée équatoriale": "Equatorial Guinea",
    "Kenya": "Kenya",
    "Lesotho": "Lesotho",
    "Libéria": "Liberia",
    "Libye": "Libya",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Mali": "Mali",
    "Maroc": "Morocco",
    "Maurice": "Mauritius",
    "Mauritanie": "Mauritania",
    "Mozambique": "Mozambique",
    "Namibie": "Namibia",
    "Niger": "Niger",
    "Nigéria": "Nigeria",
    "Ouganda": "Uganda",
    "République centrafricaine": "Central African Republic",
    "République démocratique du Congo": "Democratic Republic of the Congo",
    "République Unie de Tanzanie": "Tanzania",
    "Rwanda": "Rwanda",
    "Sao Tomé et Principe": "Sao Tome and Principe",
    "Sénégal": "Senegal",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Somalie": "Somalia",
    "Soudan": "Sudan",
    "Soudan du Sud": "South Sudan",
    "Tchad": "Chad",
    "Togo": "Togo",
    "Tunisie": "Tunisia",
    "Zambie": "Zambia",
    "Zimbabwe": "Zimbabwe",
    
    # Océanie
    "Australie": "Australia",
    "Fidji": "Fiji",
    "Îles Cook": "Cook Islands",
    "Îles Marshall": "Marshall Islands",
    "Îles Salomon": "Solomon Islands",
    "Kiribati": "Kiribati",
    "Micronésie (États fédérés de)": "Micronesia",
    "Nauru": "Nauru",
    "Nioué": "Niue",
    "Nouvelle-Calédonie": "New Caledonia",
    "Nouvelle-Zélande": "New Zealand",
    "Palaos": "Palau",
    "Papouasie-Nouvelle-Guinée": "Papua New Guinea",
    "Polynésie française": "French Polynesia",
    "Samoa": "Samoa",
    "Samoa américaines": "American Samoa",
    "Tokélaou": "Tokelau",
    "Tonga": "Tonga",
    "Tuvalu": "Tuvalu",
    "Vanuatu": "Vanuatu",
    
    # Territoires spéciaux
    "Bermudes": "Bermuda",
    "Porto Rico": "Puerto Rico",
}